# Generated by Django 5.0.6 on 2025-05-11 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(help_text='Краткое описание задачи', max_length=100, verbose_name='Название задачи')),
                ('task_description', models.CharField(blank=True, help_text='Подробное описание задачи', max_length=1000, verbose_name='Описание задачи')),
                ('task_status', models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Готова к выполнению'), ('in_progress', 'В процессе'), ('completed', 'Выполнена'), ('canceled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус задачи')),
                ('task_priority', models.CharField(choices=[('none', 'Без приоритета'), ('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='none', max_length=20, verbose_name='Приоритет задачи')),
                ('task_due_date', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения задачи')),
                ('task_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания задачи')),
                ('task_updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления задачи')),
                ('task_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-task_due_date', '-task_priority'],
            },
        ),
    ]
